create table if not exists public.shared_results (
  id bigint generated by default as identity primary key,
  saved_at timestamptz not null default timezone('utc', now()),
  recent_religion text not null,
  gender text not null,
  age integer not null check (age >= 1 and age <= 120),
  race text not null,
  city text not null,
  state_province text not null,
  country text not null,
  assessment jsonb not null
);

alter table public.shared_results enable row level security;

drop policy if exists "anon can insert shared_results" on public.shared_results;
create policy "anon can insert shared_results"
on public.shared_results
for insert
to anon
with check (
  recent_religion <> '' and
  gender <> '' and
  race <> '' and
  city <> '' and
  state_province <> '' and
  country <> '' and
  jsonb_typeof(assessment) = 'object'
);

drop policy if exists "anon can read shared_results" on public.shared_results;
create policy "anon can read shared_results"
on public.shared_results
for select
to anon
using (true);

grant usage on schema public to anon;
grant select, insert on public.shared_results to anon;